# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-25 06:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Blog_Gakki', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('nid', models.BigAutoField(primary_key=True, serialize=False)),
                ('level', models.IntegerField(verbose_name='评论楼层')),
                ('content', models.TextField(verbose_name='评论内容')),
                ('parent', models.IntegerField(verbose_name='所属楼层')),
            ],
        ),
        migrations.AlterField(
            model_name='article',
            name='article_type_id',
            field=models.IntegerField(choices=[(1, 'Python'), (2, '数据库'), (3, 'Cocos2d-x'), (4, 'unity3d')], default=None),
        ),
        migrations.AlterField(
            model_name='article',
            name='comment_count',
            field=models.IntegerField(default=0, verbose_name='评论个数'),
        ),
        migrations.AlterField(
            model_name='article',
            name='create_time',
            field=models.DateTimeField(verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='article',
            name='down_count',
            field=models.IntegerField(default=0, verbose_name='踩'),
        ),
        migrations.AlterField(
            model_name='article',
            name='read_count',
            field=models.IntegerField(default=0, verbose_name='阅读量'),
        ),
        migrations.AlterField(
            model_name='article',
            name='up_count',
            field=models.IntegerField(default=0, verbose_name='点赞'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='portrait',
            field=models.ImageField(upload_to='static/imgs/avatar_img', verbose_name='头像'),
        ),
        migrations.AddField(
            model_name='comment',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Blog_Gakki.Article'),
        ),
    ]
