# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-31 14:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Blog_Gakki', '0007_auto_20171025_0738'),
    ]

    operations = [
        migrations.CreateModel(
            name='updown',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updown', models.IntegerField(choices=[(-1, '踩'), (0, '无'), (1, '赞')], default=0, verbose_name='赞、踩、none')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Blog_Gakki.Article', verbose_name='文章')),
            ],
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='portrait',
            field=models.ImageField(blank=True, upload_to='static/imgs/avatar_img', verbose_name='头像'),
        ),
        migrations.AddField(
            model_name='updown',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Blog_Gakki.userInfo', verbose_name='用户'),
        ),
        migrations.AlterUniqueTogether(
            name='updown',
            unique_together=set([('user', 'article')]),
        ),
    ]
